name: Harvester Image Catalog Updater
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  schedule:
    - cron: '30 5 1,15 * *'
  workflow_dispatch:
    

jobs:
  get_python_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: belgaied2/update-harvester-image-catalog 
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8.12" 
        cache: "pip"
    - run: pip install -r requirements.txt
    - run: python get_image_list.py 
    - uses: actions/upload-artifact@v3
      with: 
        name: image-metadata.json
        path: image-metadata.json
  put_file_harvester:
    runs-on: ubuntu-latest
    needs: get_python_script
    steps:
    - uses: actions/checkout@v3
      with:
        repository: belgaied2/harvester-cli 
    - uses: actions/download-artifact@v3
      with:
        name: image-metadata.json
        path: image-metadata-2.json 
    - run: |
        rm image-metadata.json
        mv image-metadata-2.json image-metadata.json
        git config --global user.name "Mohamed Belgaied Hassine"
        git config --global user.email "belgaied2@hotmail.com"
        git add image-metadata.json
        git commit -m "Updating image-metadata.json"
        git push
