name: Harvester Image Catalog Updater
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  schedule:
    - cron: '30 5 1,15 * *'
  workflow_dispatch:
    

jobs:
  get_python_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: belgaied2/update-harvester-image-catalog 
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8.12" 
        cache: "pip"
    - run: pip install -r requirements.txt
    - run: python get_image_list.py 
    - run: mkdir output
    - uses: actions/upload-artifact@v3
      with: 
        name: image-metadata.json
        path: image-metadata.json
  put_file_harvester:
    runs-on: ubuntu-latest
    needs: get_python_script
    steps:
    - name: Clone repo harvester-cli 
      uses: actions/checkout@v3
      with:
        repository: belgaied2/harvester-cli 
    - name: Download image-metadata.json from previous Job
      uses: actions/download-artifact@v3
      with:
        name: image-metadata.json
        path: output/image-metadata.json 
    - name: push to other repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: output/
        destination-github-username: 'belgaied2'
        destination-repository-name: 'harvester-cli'
        user-email: belgaied2@hotmail.com
        target-branch: master